name: Infection

on:
  pull_request:
    branches:
      - develop
    paths:
      - '**.php'
      - 'composer.*'
      - 'phpunit*'
      - '.github/workflows/infection.yml'

jobs:
  infection:
    uses: codeigniter4/.github/.github/workflows/infection.yml@main
