name: PHPCPD

on:
  pull_request:
    branches:
      - develop
    paths:
      - '**.php'
      - '.github/workflows/phpcpd.yml'
  push:
    branches:
      - develop
    paths:
      - '**.php'
      - '.github/workflows/phpcpd.yml'

jobs:
  phpcpd:
    uses: codeigniter4/.github/.github/workflows/phpcpd.yml@main
    with:
      dirs: "src/ tests/"
