name: PHPCSFixer

on:
  pull_request:
    branches:
      - develop
    paths:
      - '**.php'
      - '.github/workflows/phpcsfixer.yml'
  push:
    branches:
      - develop
    paths:
      - '**.php'
      - '.github/workflows/phpcsfixer.yml'

jobs:
  phpcsfixer:
    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.2', '8.4']

    uses: codeigniter4/.github/.github/workflows/phpcsfixer.yml@CI46
    with:
      php-version: ${{ matrix.php-version }}
