name: Rector

on:
  pull_request:
    branches:
      - develop
    paths:
      - '**.php'
      - 'composer.*'
      - 'rector.php'
      - '.github/workflows/rector.yml'
  push:
    branches:
      - develop
    paths:
      - '**.php'
      - 'composer.*'
      - 'rector.php'
      - '.github/workflows/rector.yml'

jobs:
  rector:
    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.2', '8.4']

    uses: codeigniter4/.github/.github/workflows/rector.yml@CI46
    with:
      php-version: ${{ matrix.php-version }}
